// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UUID        string         `gorm:"column:uuid;type:uuid;primaryKey;default:gen_random_uuid()" json:"uuid"`
	Name        string         `gorm:"column:name;type:character varying(255);not null;index:idx_users_name,priority:1" json:"name"`
	Email       string         `gorm:"column:email;type:character varying(255);not null;uniqueIndex:idx_users_email,priority:1" json:"email"`
	Password    string         `gorm:"column:password;type:character varying(255);not null" json:"password"`
	PhoneNumber *string        `gorm:"column:phone_number;type:character varying(255);uniqueIndex:idx_users_phone_number,priority:1" json:"phone_number"`
	Photo       *string        `gorm:"column:photo;type:character varying(255)" json:"photo"`
	CreatedAt   *time.Time     `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_users_deleted_at,priority:1" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
