version: "0.1"
database:
  dsn: "host=localhost user=alfredopatriciustarigan password=test dbname=tabunganku port=5432 sslmode=disable TimeZone=UTC"
  db: "postgres"
  tables: []
  outPath: "./pkg/models"
  outFile: ""
  withUnitTest: false
  modelPkgName: "models"
  fieldNullable: true
  fieldWithIndexTag: true
  fieldWithTypeTag: true
  onlyModel: true
  excludeTables: ["goose_db_version", "migrations"]
